# Form implementation generated from reading ui file 'formulario.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(441, 545)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_titulo = QtWidgets.QLabel(parent=self.centralwidget)
        self.txt_titulo.setGeometry(QtCore.QRect(60, 10, 330, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.txt_titulo.setFont(font)
        self.txt_titulo.setObjectName("txt_titulo")
        self.gb_informacionPersonal = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.gb_informacionPersonal.setGeometry(QtCore.QRect(30, 40, 381, 221))
        self.gb_informacionPersonal.setObjectName("gb_informacionPersonal")
        self.txt_nombre = QtWidgets.QLabel(parent=self.gb_informacionPersonal)
        self.txt_nombre.setGeometry(QtCore.QRect(10, 30, 49, 16))
        self.txt_nombre.setObjectName("txt_nombre")
        self.le_nombre = QtWidgets.QLineEdit(parent=self.gb_informacionPersonal)
        self.le_nombre.setGeometry(QtCore.QRect(60, 30, 291, 21))
        self.le_nombre.setObjectName("le_nombre")
        self.le_correo = QtWidgets.QLineEdit(parent=self.gb_informacionPersonal)
        self.le_correo.setGeometry(QtCore.QRect(50, 60, 291, 21))
        self.le_correo.setObjectName("le_correo")
        self.txt_nombre_2 = QtWidgets.QLabel(parent=self.gb_informacionPersonal)
        self.txt_nombre_2.setGeometry(QtCore.QRect(10, 60, 36, 16))
        self.txt_nombre_2.setObjectName("txt_nombre_2")
        self.le_contrasena = QtWidgets.QLineEdit(parent=self.gb_informacionPersonal)
        self.le_contrasena.setGeometry(QtCore.QRect(80, 90, 141, 21))
        self.le_contrasena.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.le_contrasena.setObjectName("le_contrasena")
        self.txt_nombre_3 = QtWidgets.QLabel(parent=self.gb_informacionPersonal)
        self.txt_nombre_3.setGeometry(QtCore.QRect(10, 90, 60, 16))
        self.txt_nombre_3.setObjectName("txt_nombre_3")
        self.txt_nombre_4 = QtWidgets.QLabel(parent=self.gb_informacionPersonal)
        self.txt_nombre_4.setGeometry(QtCore.QRect(10, 120, 29, 16))
        self.txt_nombre_4.setObjectName("txt_nombre_4")
        self.sb_edad = QtWidgets.QSpinBox(parent=self.gb_informacionPersonal)
        self.sb_edad.setGeometry(QtCore.QRect(50, 120, 42, 22))
        self.sb_edad.setMinimum(1)
        self.sb_edad.setMaximum(100)
        self.sb_edad.setObjectName("sb_edad")
        self.txt_pais = QtWidgets.QLabel(parent=self.gb_informacionPersonal)
        self.txt_pais.setGeometry(QtCore.QRect(10, 150, 24, 16))
        self.txt_pais.setObjectName("txt_pais")
        self.txt_genero = QtWidgets.QLabel(parent=self.gb_informacionPersonal)
        self.txt_genero.setGeometry(QtCore.QRect(10, 180, 41, 16))
        self.txt_genero.setObjectName("txt_genero")
        self.rb_masculino = QtWidgets.QRadioButton(parent=self.gb_informacionPersonal)
        self.rb_masculino.setGeometry(QtCore.QRect(60, 180, 78, 20))
        self.rb_masculino.setObjectName("rb_masculino")
        self.rb_femenino = QtWidgets.QRadioButton(parent=self.gb_informacionPersonal)
        self.rb_femenino.setGeometry(QtCore.QRect(140, 180, 76, 20))
        self.rb_femenino.setObjectName("rb_femenino")
        self.rb_na = QtWidgets.QRadioButton(parent=self.gb_informacionPersonal)
        self.rb_na.setGeometry(QtCore.QRect(220, 180, 120, 20))
        self.rb_na.setObjectName("rb_na")
        self.cb_paises = QtWidgets.QComboBox(parent=self.gb_informacionPersonal)
        self.cb_paises.setGeometry(QtCore.QRect(40, 150, 108, 22))
        self.cb_paises.setObjectName("cb_paises")
        self.cb_paises.addItem("")
        self.cb_paises.addItem("")
        self.cb_paises.addItem("")
        self.cb_paises.addItem("")
        self.cb_paises.addItem("")
        self.cb_paises.addItem("")
        self.cb_paises.addItem("")
        self.cb_paises.addItem("")
        self.gb_preferenciasEIntereses = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.gb_preferenciasEIntereses.setGeometry(QtCore.QRect(30, 260, 381, 151))
        self.gb_preferenciasEIntereses.setObjectName("gb_preferenciasEIntereses")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.gb_preferenciasEIntereses)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 30, 91, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.cb_lectura = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.cb_lectura.setObjectName("cb_lectura")
        self.gridLayout.addWidget(self.cb_lectura, 0, 0, 1, 1)
        self.cb_tecnologia = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.cb_tecnologia.setObjectName("cb_tecnologia")
        self.gridLayout.addWidget(self.cb_tecnologia, 1, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(parent=self.gb_preferenciasEIntereses)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(150, 30, 91, 51))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cb_musica = QtWidgets.QCheckBox(parent=self.gridLayoutWidget_3)
        self.cb_musica.setObjectName("cb_musica")
        self.gridLayout_3.addWidget(self.cb_musica, 0, 0, 1, 1)
        self.cb_artes = QtWidgets.QCheckBox(parent=self.gridLayoutWidget_3)
        self.cb_artes.setObjectName("cb_artes")
        self.gridLayout_3.addWidget(self.cb_artes, 1, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(parent=self.gb_preferenciasEIntereses)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(250, 30, 81, 21))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cb_deportes = QtWidgets.QCheckBox(parent=self.gridLayoutWidget_4)
        self.cb_deportes.setObjectName("cb_deportes")
        self.gridLayout_4.addWidget(self.cb_deportes, 0, 0, 1, 1)
        self.txt_nA = QtWidgets.QLabel(parent=self.gb_preferenciasEIntereses)
        self.txt_nA.setGeometry(QtCore.QRect(10, 90, 96, 16))
        self.txt_nA.setObjectName("txt_nA")
        self.le_nA = QtWidgets.QLineEdit(parent=self.gb_preferenciasEIntereses)
        self.le_nA.setGeometry(QtCore.QRect(10, 110, 351, 21))
        self.le_nA.setText("")
        self.le_nA.setObjectName("le_nA")
        self.gb_terminosYC = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.gb_terminosYC.setGeometry(QtCore.QRect(30, 420, 381, 21))
        self.gb_terminosYC.setTitle("")
        self.gb_terminosYC.setObjectName("gb_terminosYC")
        self.cb_terminosYC = QtWidgets.QCheckBox(parent=self.gb_terminosYC)
        self.cb_terminosYC.setGeometry(QtCore.QRect(100, 0, 187, 20))
        self.cb_terminosYC.setObjectName("cb_terminosYC")
        self.gb_botones = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.gb_botones.setGeometry(QtCore.QRect(30, 450, 381, 51))
        self.gb_botones.setTitle("")
        self.gb_botones.setObjectName("gb_botones")
        self.pb_registrar = QtWidgets.QPushButton(parent=self.gb_botones)
        self.pb_registrar.setEnabled(False)
        self.pb_registrar.setGeometry(QtCore.QRect(20, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_registrar.setFont(font)
        self.pb_registrar.setObjectName("pb_registrar")
        self.pb_limpiar = QtWidgets.QPushButton(parent=self.gb_botones)
        self.pb_limpiar.setGeometry(QtCore.QRect(150, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_limpiar.setFont(font)
        self.pb_limpiar.setObjectName("pb_limpiar")
        self.pb_cancelar = QtWidgets.QPushButton(parent=self.gb_botones)
        self.pb_cancelar.setGeometry(QtCore.QRect(270, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_cancelar.setFont(font)
        self.pb_cancelar.setObjectName("pb_cancelar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 441, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_titulo.setText(_translate("MainWindow", "Formulario de Registro de Usuario"))
        self.gb_informacionPersonal.setTitle(_translate("MainWindow", "Informacion Personal"))
        self.txt_nombre.setText(_translate("MainWindow", "Nombre:"))
        self.txt_nombre_2.setText(_translate("MainWindow", "Correo"))
        self.txt_nombre_3.setText(_translate("MainWindow", "Contraseña"))
        self.txt_nombre_4.setText(_translate("MainWindow", "Edad:"))
        self.txt_pais.setText(_translate("MainWindow", "Pais:"))
        self.txt_genero.setText(_translate("MainWindow", "Genero:"))
        self.rb_masculino.setText(_translate("MainWindow", "Masculino"))
        self.rb_femenino.setText(_translate("MainWindow", "Femenino"))
        self.rb_na.setText(_translate("MainWindow", "Prefiero no decirlo"))
        self.cb_paises.setItemText(0, _translate("MainWindow", "México"))
        self.cb_paises.setItemText(1, _translate("MainWindow", "Argentina"))
        self.cb_paises.setItemText(2, _translate("MainWindow", "Brasil"))
        self.cb_paises.setItemText(3, _translate("MainWindow", "Canadá"))
        self.cb_paises.setItemText(4, _translate("MainWindow", "Colombia"))
        self.cb_paises.setItemText(5, _translate("MainWindow", "Chile"))
        self.cb_paises.setItemText(6, _translate("MainWindow", "Estados Unidos "))
        self.cb_paises.setItemText(7, _translate("MainWindow", "España"))
        self.gb_preferenciasEIntereses.setTitle(_translate("MainWindow", "Preferencias e intereses"))
        self.cb_lectura.setText(_translate("MainWindow", "Lectura"))
        self.cb_tecnologia.setText(_translate("MainWindow", "Tecnologia"))
        self.cb_musica.setText(_translate("MainWindow", "Musica"))
        self.cb_artes.setText(_translate("MainWindow", "Artes"))
        self.cb_deportes.setText(_translate("MainWindow", "Deportes"))
        self.txt_nA.setText(_translate("MainWindow", "Notas adicionales:"))
        self.cb_terminosYC.setText(_translate("MainWindow", "Acepto terminos y condiciones"))
        self.pb_registrar.setText(_translate("MainWindow", "Registrar"))
        self.pb_limpiar.setText(_translate("MainWindow", "Limpiar"))
        self.pb_cancelar.setText(_translate("MainWindow", "Cancelar"))


class VistaRegistro(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        
    def obtener_datos_formulario(self) -> dict:
        """Obtiene todos los datos del formulario y los retorna en un diccionario"""
        datos = {}
        
        datos['nombre'] = self.le_nombre.text().strip()
        datos['correo'] = self.le_correo.text().strip()
        datos['contrasena'] = self.le_contrasena.text()
        datos['edad'] = self.sb_edad.value()
        datos['pais'] = self.cb_paises.currentText()
        
        if self.rb_masculino.isChecked():
            datos['genero'] = 'Masculino'
        elif self.rb_femenino.isChecked():
            datos['genero'] = 'Femenino'
        elif self.rb_na.isChecked():
            datos['genero'] = 'Prefiero no decirlo'
        else:
            datos['genero'] = ''
        
        intereses = []
        if self.cb_lectura.isChecked():
            intereses.append('Lectura')
        if self.cb_musica.isChecked():
            intereses.append('Musica')
        if self.cb_deportes.isChecked():
            intereses.append('Deportes')
        if self.cb_tecnologia.isChecked():
            intereses.append('Tecnologia')
        if self.cb_artes.isChecked():
            intereses.append('Artes')
        datos['intereses'] = intereses
        
        datos['acepta_terminos'] = self.cb_terminosYC.isChecked()
        
        datos['notas_adicionales'] = self.le_nA.text().strip()
        
        return datos
    
    def mostrar_error(self, mensaje: str):
        """Muestra un mensaje de error al usuario"""
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
        msg.setWindowTitle("Error")
        msg.setText(mensaje)
        msg.exec()
    
    def mostrar_exito(self, mensaje: str):
        """Muestra un mensaje de éxito al usuario"""
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Icon.Information)
        msg.setWindowTitle("Éxito")
        msg.setText(mensaje)
        msg.exec()
    
    def limpiar_formulario(self):
        """Limpia todos los campos del formulario"""
        self.le_nombre.clear()
        self.le_correo.clear()
        self.le_contrasena.clear()
        self.le_nA.clear()
        
        self.sb_edad.setValue(1)
        
        self.cb_paises.setCurrentIndex(0)
        
        self.rb_masculino.setAutoExclusive(False)
        self.rb_masculino.setChecked(False)
        self.rb_femenino.setChecked(False)
        self.rb_na.setChecked(False)
        self.rb_masculino.setAutoExclusive(True)
        
        self.cb_lectura.setChecked(False)
        self.cb_musica.setChecked(False)
        self.cb_deportes.setChecked(False)
        self.cb_tecnologia.setChecked(False)
        self.cb_artes.setChecked(False)
        self.cb_terminosYC.setChecked(False)
        
        self.habilitar_boton_registro(False)
    
    def habilitar_boton_registro(self, habilitar: bool):
        """Habilita o deshabilita el botón de registro"""
        self.pb_registrar.setEnabled(habilitar)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = VistaRegistro()
    MainWindow.show()
    sys.exit(app.exec())